#lexik_jwt_authentication:
#    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
 #   public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
  #  pass_phrase: '%env(JWT_PASSPHRASE)%'

lexik_jwt_authentication:
    private_key_path: '%kernel.project_dir%/config/jwt/private.pem'
    public_key_path:  '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase:      '%env(JWT_PASSPHRASE)%'
    user_identity_field : email

