vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /uploads/images/cars
            upload_destination: '%kernel.project_dir%/public/uploads/images/cars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true
